### PR TITLE
Ripple effect from QuickPaper

### PR DESCRIPTION
**Pull request by iBelieve**
**_Depends on #3_**

This will be used in the +material implementation of list items and other components. I put it in the `Fluid.Material` module so it can be directly imported into +material components in the shell, in addition to local +material components in Fluid. 

Once we've used the component for a while and ironed out any bugs or missing functionality, I can work on upstreaming it into Controls 2.

### CODE REVIEW

**Comment by plfiorini** [comment]
can we keep Icon for xdg icon theme icons?

**Comment by plfiorini** [comment]
anyways do not close and resubmit this PR for develop, i've tested and i can manually apply to develop even if it was meant for master (at the moment it still does the fast forward)

**Comment by iBelieve** [comment]
@plfiorini I think it would be best to use one common Icon component, as we can use it in various places without having to have two separate components for material and xdg icons, for example in the ListItem component.

Also, I'm in the Hawaii slack team if you want to discuss anything in there versus going back and forth in comments.

**Comment by plfiorini** [comment]
Merged

**Pull request closed without merging**
